apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deployment-example
  template:
    metadata:
      labels:
        app: nginx-deployment-example
    spec:
      containers:
        - name: nginx
          image: uncut/nginx-grape:$WORKFLOW_ID
      imagePullSecrets:
        - name: dockerhub

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: nginx-deployment-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
